# Site settings
title: "Markham Shofner"
email: markham.shofner@gmail.com
description: "A blog."
baseurl: ""
url: "http://markhamshofner.github.io"
title_description: "Web developer with a focus on JavaScript. Also experienced in d3, HTML 5, CSS3, jQuery, Ruby on Rails, and a few more. Former management consultant. Professional frisbee player. General derp who loves to learn - anything from useless trivia to new technologies. I live in Washington, DC."
title_image: "http://i.imgur.com/AmqhzdF.jpg"
google_analytics:
disqus_account:
github_repository: https://markhamshofner.github.io
addthis_id:
post_limit: 5

# Social usernames/URLs
twitter_username: MarkhamShofner
github_username:  MarkhamShofner
linkedin_link: http://www.linkedin.com/in/markhamshofner
google_plus_link:
stackoverflow_link:

# Footer
footer_left: "Template made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
