# Site settings
title: "Markham Shofner"
email: markham.shofner@gmail.com
description: "A blog."
baseurl: ""
url: "http://markhamshofner.github.io"
title_description: "Full stack web developer with a JavaScript focus. Also experienced in Node, Angular, Express, HTML5, CSS3, D3, jQuery, Ruby on Rails, and a few more. Former management consultant. Professional frisbee player. General enthusiast - anything from sports trivia, through fantasy novels, to new technologies."
title_image: "https://i.imgur.com/AmqhzdF.jpg"
google_analytics:
disqus_account:
github_repository: https://markhamshofner.github.io
addthis_id:
post_limit: 5

# Social usernames/URLs
twitter_username: MarkhamShofner
github_username:  MarkhamShofner
linkedin_link: http://www.linkedin.com/in/markhamshofner
google_plus_link:
stackoverflow_link:

# Footer
footer_left: #"Template made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: Powered by Jekyll using Carte Noire.
  #"&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
